### ISSUE TITLE
Trap keyboard interrupt when prompted for reason

### ISSUE THREAD

**Issue by dewski** [cased/cli#7]
Currently:

```
> command help
[cased 🔒] Running under Cased.
[cased 🔒] Please enter a reason for access: ^CTraceback (most recent call last):
  File "/usr/local/bin/cased", line 487, in <module>
    run(program, args[3:])
  File "/usr/local/bin/cased", line 426, in run
    Client(program).execute(program_args, app_token, deny_if_unreachable, user_token)
  File "/usr/local/Cellar/cased/0.6.1/libexec/lib/python3.9/site-packages/cguard/core/client.py", line 145, in execute
    self._handle_response(
  File "/usr/local/Cellar/cased/0.6.1/libexec/lib/python3.9/site-packages/cguard/core/client.py", line 60, in _handle_response
    reason = self._prompt_for_reason()
  File "/usr/local/Cellar/cased/0.6.1/libexec/lib/python3.9/site-packages/cguard/core/client.py", line 30, in _prompt_for_reason
    reason = input("[cased 🔒] Please enter a reason for access: ")
KeyboardInterrupt
```

Would be nice for it to be:

```
> command help
[cased 🔒] Running under Cased.
[cased 🔒] Please enter a reason for access: ^C
```

**Comment by tnm** [comment]
Yeah we do that when waiting, but I can add it there too.

**Comment by tnm** [comment]
<img width="393" alt="Screen Shot 2021-03-25 at 12 29 39 PM" src="https://user-images.githubusercontent.com/126905/112532225-cc13e000-8d65-11eb-9f9b-926f9a3523b5.png">

**Comment by tnm** [comment]
Done in https://github.com/cased/cli/commit/f830702ce720275d0a8216f11f84df75b005a8dd.
